# Generated by Django 4.1.2 on 2022-11-01 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 11, 1, 14, 42, 37, 572569, tzinfo=datetime.timezone.utc))),
                ('text', models.CharField(blank=True, max_length=500)),
                ('tags', models.CharField(choices=[('Text', 'TEXT'), ('Code snippet', 'CODE SNIPPET'), ('Screenshot', 'SCREENSHOT')], default='Text', max_length=50)),
            ],
        ),
    ]
