# Generated by Django 4.1.2 on 2023-01-24 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("entries", "0003_alter_entry_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="entry",
            name="tags",
            field=models.CharField(
                choices=[
                    ("Note", "Note"),
                    ("Code snippet", "CODE SNIPPET"),
                    ("Screenshot", "SCREENSHOT"),
                    ("Achievement", "ACHIEVEMENT"),
                ],
                default="Note",
                max_length=50,
            ),
        ),
    ]
